export {SettingsService} from './settings/settings.service';
export {SharedService} from './shared/shared.service';
export {SiderbarService} from './shared/siderbar.service';
export {UsuarioService} from './usuario/usuario.service';
export {LoginGuardGuard} from './guards/login-guard.guard';
export {SubirArchivoService} from './subir-archivo/subir-archivo.service';
export {HospitalService} from './hospital/hospital.service';
export {MedicoService} from './medico/medico.service';
export {AdminGuard} from './guards/admin.guard';
